### ISSUE TITLE
能否增加anaconda/miniconda镜像？

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#1]
**类别**：
申请新增镜像

**镜像名**：
anaconda

**上游路径**：
https://repo.continuum.io/

**镜像简介**：
Anaconda 是一个用于科学计算的 Python 发行版，支持 Linux, Mac, Windows, 包含了众多流行的科学计算、数据分析的 Python 包。它可以高效的建立与系统相对独立的python环境，安装并管理python包，且可以用于R软件及包的建立与管理。

清华大学和上海大学都有其镜像站：
<https://mirror.tuna.tsinghua.edu.cn/help/anaconda/>
<https://mirrors.shu.edu.cn/anaconda/>

**Comment by htfy96** [comment]
我们会在近期加入这个镜像

**Comment by specter119** [comment]
@htfy96 非常感谢！

**Comment by htfy96** [comment]
请问@specter119 除了官方的channel以外，是否还需要第三方的channel（如PyTorch、https://anaconda.org/intel）之类的？

**Comment by htfy96** [comment]
另外Anaconda的镜像也有一些版权问题：

根据 https://repo.continuum.io/pkgs/

> Anaconda and Miniconda are trademarks of Anaconda, Inc. Public mirrors of this are not allowed without express permission from Anaconda, Inc. For private mirrors and technical support, we encourage you to look at Anaconda Enterprise and Anaconda Support.

目前来看tuna和shu都是无证上岗的情况……一种fallback的策略是建立反代

**Comment by specter119** [comment]
@htfy96 
谢谢，对于第三方的库，我个人意见:

[conda-forge](https://anaconda.org/conda-forge) 是必要的，这个是官方源的极好的补充。
[matsci](https://anaconda.org/matsci) 虽然小众，但对于我们组里是必须的，用于材料高通量计算。

我的需求基本只有这些了。

至于机器学习比较火的库(我用的并不多，基本只用scikit-learn)，tensorflow包含在conda-forge里面，可以为pytorch加上 [soumith](https://anaconda.org/soumith)。

至于intel官方的源，需要的人应该不多，因为conda里面的官方库都是会装mkl并且加mkl编译的。

**Comment by htfy96** [comment]
已经添加：https://mirrors.sjtug.org/anaconda/ 等待同步完成。目前包括的源有：
```yaml
      pkgs/main/linux-64: https://repo.continuum.io/pkgs/main/linux-64/
      pkgs/main/linux-32: https://repo.continuum.io/pkgs/main/linux-32/
      pkgs/main/linux-ppc64le: https://repo.continuum.io/pkgs/main/linux-ppc64le/
      pkgs/main/osx-64: https://repo.continuum.io/pkgs/main/osx-64/
      pkgs/main/win-64: https://repo.continuum.io/pkgs/main/win-64/
      pkgs/main/win-32: https://repo.continuum.io/pkgs/main/win-32/
      pkgs/main/noarch: https://repo.continuum.io/pkgs/main/noarch/
      pkgs/free/linux-64: https://repo.continuum.io/pkgs/free/linux-64/
      pkgs/free/linux-32: https://repo.continuum.io/pkgs/free/linux-32/
      pkgs/free/linux-armv6l: https://repo.continuum.io/pkgs/free/linux-armv6l/
      pkgs/free/linux-armv7l: https://repo.continuum.io/pkgs/free/linux-armv7l/
      pkgs/free/linux-ppc64le: https://repo.continuum.io/pkgs/free/linux-ppc64le/
      pkgs/free/osx-64: https://repo.continuum.io/pkgs/free/osx-64/
      pkgs/free/osx-32: https://repo.continuum.io/pkgs/free/osx-32/
      pkgs/free/win-64: https://repo.continuum.io/pkgs/free/win-64/
      pkgs/free/win-32: https://repo.continuum.io/pkgs/free/win-32/
      pkgs/free/noarch: https://repo.continuum.io/pkgs/free/noarch/
      pkgs/r/linux-64: https://repo.continuum.io/pkgs/r/linux-64/
      pkgs/r/linux-32: https://repo.continuum.io/pkgs/r/linux-32/
      pkgs/r/linux-armv6l: https://repo.continuum.io/pkgs/r/linux-armv6l/
      pkgs/r/linux-armv7l: https://repo.continuum.io/pkgs/r/linux-armv7l/
      pkgs/r/linux-ppc64le: https://repo.continuum.io/pkgs/r/linux-ppc64le/
      pkgs/r/osx-64: https://repo.continuum.io/pkgs/r/osx-64/
      pkgs/r/osx-32: https://repo.continuum.io/pkgs/r/osx-32/
      pkgs/r/win-64: https://repo.continuum.io/pkgs/r/win-64/
      pkgs/r/win-32: https://repo.continuum.io/pkgs/r/win-32/
      pkgs/r/noarch: https://repo.continuum.io/pkgs/r/noarch/
      pkgs/pro/linux-64: https://repo.continuum.io/pkgs/pro/linux-64/
      pkgs/pro/linux-32: https://repo.continuum.io/pkgs/pro/linux-32/
      pkgs/pro/linux-armv6l: https://repo.continuum.io/pkgs/pro/linux-armv6l/
      pkgs/pro/linux-armv7l: https://repo.continuum.io/pkgs/pro/linux-armv7l/
      pkgs/pro/linux-ppc64le: https://repo.continuum.io/pkgs/pro/linux-ppc64le/
      pkgs/pro/osx-64: https://repo.continuum.io/pkgs/pro/osx-64/
      pkgs/pro/osx-32: https://repo.continuum.io/pkgs/pro/osx-32/
      pkgs/pro/win-64: https://repo.continuum.io/pkgs/pro/win-64/
      pkgs/pro/win-32: https://repo.continuum.io/pkgs/pro/win-32/
      pkgs/pro/noarch: https://repo.continuum.io/pkgs/pro/noarch/
      pkgs/mro/linux-64: https://repo.continuum.io/pkgs/mro/linux-64/
      pkgs/mro/linux-32: https://repo.continuum.io/pkgs/mro/linux-32/
      pkgs/mro/linux-armv6l: https://repo.continuum.io/pkgs/mro/linux-armv6l/
      pkgs/mro/linux-armv7l: https://repo.continuum.io/pkgs/mro/linux-armv7l/
      pkgs/mro/linux-ppc64le: https://repo.continuum.io/pkgs/mro/linux-ppc64le/
      pkgs/mro/osx-64: https://repo.continuum.io/pkgs/mro/osx-64/
      pkgs/mro/osx-32: https://repo.continuum.io/pkgs/mro/osx-32/
      pkgs/mro/win-64: https://repo.continuum.io/pkgs/mro/win-64/
      pkgs/mro/win-32: https://repo.continuum.io/pkgs/mro/win-32/
      pkgs/mro/noarch: https://repo.continuum.io/pkgs/mro/noarch/
      pkgs/msys2/win-64: https://repo.continuum.io/pkgs/msys2/win-64/
      pkgs/msys2/win-32: https://repo.continuum.io/pkgs/msys2/win-32/
      cloud/conda-forge/noarch: https://conda.anaconda.org/conda-forge/noarch/
      cloud/conda-forge/linux-64: https://conda.anaconda.org/conda-forge/linux-64/
      cloud/conda-forge/osx-64: https://conda.anaconda.org/conda-forge/osx-64/
      cloud/conda-forge/win-64: https://conda.anaconda.org/conda-forge/win-64/
      cloud/bioconda/noarch: https://conda.anaconda.org/bioconda/noarch/
      cloud/bioconda/linux-64: https://conda.anaconda.org/bioconda/linux-64/
      cloud/bioconda/osx-64: https://conda.anaconda.org/bioconda/osx-64/
      cloud/menpo/noarch: https://conda.anaconda.org/menpo/noarch/
      cloud/menpo/linux-64: https://conda.anaconda.org/menpo/linux-64/
      cloud/menpo/osx-64: https://conda.anaconda.org/menpo/osx-64/
      cloud/menpo/win-64: https://conda.anaconda.org/menpo/win-64/
      cloud/matsci/noarch: https://conda.anaconda.org/matsci/noarch/
      cloud/matsci/linux-64: https://conda.anaconda.org/matsci/linux-64/
      cloud/matsci/osx-64: https://conda.anaconda.org/matsci/osx-64/
      cloud/matsci/win-64: https://conda.anaconda.org/matsci/win-64/
      cloud/soumith/linux-64: https://conda.anaconda.org/soumith/linux-64/
      cloud/soumith/osx-64: https://conda.anaconda.org/soumith/osx-64/
```
