### ISSUE TITLE
Pip install 报 403 错误

### ISSUE THREAD

**Issue by wangziling** [sjtug/mirror-requests#329]
```shell
E:\Codes>pip install maturin
Looking in indexes: https://mirror.sjtu.edu.cn/pypi/web/simple
Collecting maturin
  ERROR: HTTP error 403 while getting https://mirror.sjtu.edu.cn/pypi-packages/02/1b/839faa4c827d1dc44b2d98d18765bc4440495a5627c6a5470065fc01cfb9/maturin-1.3.1-py3-none-win_amd64.whl#sha256=871268417d6b3e2b46018c54a0522efc018bc4918b885d005df90b338e0674c7 (from https://mirror.sjtu.edu.cn/pypi/web/simple/maturin/) (requires-python:>=3.7)
ERROR: Could not install requirement maturin from https://mirror.sjtu.edu.cn/pypi-packages/02/1b/839faa4c827d1dc44b2d98d18765bc4440495a5627c6a5470065fc01cfb9/maturin-1.3.1-py3-none-win_amd64.whl#sha256=871268417d6b3e2b46018c54a0522efc018bc4918b885d005df90b338e0674c7 because of HTTP error 403 Client Error: Forbidden for url: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/02/1b/839faa4c827d1dc44b2d98d18765bc4440495a5627c6a5470065fc01cfb9/maturin-1.3.1-py3-none-win_amd64.whl for URL https://mirror.sjtu.edu.cn/pypi-packages/02/1b/839faa4c827d1dc44b2d98d18765bc4440495a5627c6a5470065fc01cfb9/maturin-1.3.1-py3-none-win_amd64.whl#sha256=871268417d6b3e2b46018c54a0522efc018bc4918b885d005df90b338e0674c7 (from https://mirror.sjtu.edu.cn/pypi/web/simple/maturin/) (requires-python:>=3.7)

E:\Codes>python --version
Python 3.11.5

E:\Codes>conda --version
conda 23.9.0

E:\Codes>pip --version
pip 23.3.1 from E:\Environments\Anaconda\envs\python311\Lib\site-packages\pip (python 3.11)
```

# Pip 设置
`pip.ini`
```ini
[global]
index-url = https://mirror.sjtu.edu.cn/pypi/web/simple
cache-dir = E:\\Environments\\Anaconda\\pip\\cache
```

# Conda 设置
```yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/free
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/main
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/mro
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/msys2
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/r
  - https://mirror.sjtu.edu.cn/anaconda/pkgs/pro
custom_channels:
  conda-forge: https://mirror.sjtu.edu.cn/anaconda/cloud/
  msys2: https://mirror.sjtu.edu.cn/anaconda/cloud/
  bioconda: https://mirror.sjtu.edu.cn/anaconda/cloud/
  menpo: https://mirror.sjtu.edu.cn/anaconda/cloud/
  pytorch: https://mirror.sjtu.edu.cn/anaconda/cloud/
  pytorch-lts: https://mirror.sjtu.edu.cn/anaconda/cloud/
  pytorch-test: https://mirror.sjtu.edu.cn/anaconda/cloud/
  simpleitk: https://mirror.sjtu.edu.cn/anaconda/cloud/
  atztogo: https://mirror.sjtu.edu.cn/anaconda/cloud/
  viscid-hub: https://mirror.sjtu.edu.cn/anaconda/cloud/
  soumith: https://mirror.sjtu.edu.cn/anaconda/cloud/
```
