### ISSUE TITLE
conda/atztogo 404

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#53]
**类别**：Bug

```
Collecting package metadata: failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: atztogo
  channel url: https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/atztogo
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

当 config 里有 atztogo 里更新 conda 就会报这个错，其他的 sjtug 的 conda channel 就不会。
另外比较奇怪的是，直接复制  https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/atztogo 会大概率直接跳到  https://mirrors.sjtug.sjtu.edu.cn/cloud/atztogo 返回404。

**Comment by SkyZH** [comment]
这个和 #49 是一样的问题，可能要等 caddy 上游解决。先关了。

**Comment by SkyZH** [comment]
你可以在 channel url 后面再加一个 / 试试看吗？

**Comment by SkyZH** [comment]
https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/atztogo/

**Comment by specter119** [comment]
@SkyZH 
我自己的 `~/.condarc` 改的比较多，改源部分是这么写的。

```yaml
channel_alias: https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud
custom_multichannels:
  sjtu:
    - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main
    - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free
    - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/r
    - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/pro
channels:
  - sjtu
  - defaults
  - conda-forge
  - matsci
  #- atztogo
  - viscid-hub
```
`- atztogo` 改为 `- atztogo/` 没有用

可能和 #49 的问题不完全一样，因为我只有 `atztogo` 这个 channel 有问题。剩下所有的 channel 都是正常的。
