### ISSUE TITLE
anaconda 源补充说明

### ISSUE THREAD

**Issue by specter119** [sjtug/mirror-requests#77]
https://github.com/sjtug/mirror-requests/issues/56 所述情况，基本确定是sjtug的bug了。之前禁止自动升级的方法经测已不再适用。
意外发现了一个 conda 4.8.2 之后的新方法，可以继续将 sjtug 作为 conda 的主源。步骤如下：
1. 将 conda 升级到 4.8.2 以上(4.8.1未测试，4.8.2，4.8.3已经已经测试通过)。
2. 将配置文件中主源相关的部分改为：

for linux or mac
```yaml
custom_multichannels:
  sjtu:
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/main
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/r
channels:
  # - sjtu
  - defaults
```
for windows:
```yaml
custom_multichannels:
  sjtu:
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/main
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/r
    - https://anaconda.mirrors.sjtug.sjtu.edu.cn/pkgs/msys2
channels:
  # - sjtu
  - defaults
```

然后测试能否正常升级即可。在4.8.2以上的版本，三个平台均测试有效。在[四楼](https://github.com/sjtug/sjtug.github.io/issues/12#issuecomment-640154392)是我自己的完整配置以及该配置的解释。
